defaults: &defaults
  skipDownload: no
  skipInstall: no

rider:
  <<: *defaults
  name: "Rider"
  download: "https://download.jetbrains.com/rider/JetBrains.Rider-2024.3.4.exe"
  installArgs:
    - "/S"
    - "/CONFIG=${SETUP_PROJ}/src/rider/silent.config"
    - "/LOG=${TMP}/rider_install.log"
    - "/D=${IDES}/jetbrains/Rider"
